baseURL = ''
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
title = 'Présentation By Bertrand Keller'
theme = 'overgo'

[params]
  organisation = "La direction générale des douanes et droits indirects"

